name: link-check
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verificar links internos
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --base . ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
